name: Deploy Contracts After PR Merge to main branch

on:
  push:
    branches:
      - "main"

jobs:
  deploy-contracts-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::234736309150:role/github_connect
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Deploy all contracts on UAT environment
        run: echo "PR Just merged; again confirming"
